# Generated by Django 4.2.7 on 2023-12-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('task_name', models.CharField(max_length=200)),
                ('assigned_to', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('due_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='L', max_length=8)),
            ],
        ),
    ]
